using System;

namespace Programs
{
    class Program
    {
        static void Main(string[] args)
        {
            // Write C# code to declare a variable to store the age of a person.
            Q.q1();

            // Write a C# program that asks the user to input three integer values and find the greatest value of the three values.
            // Q.q2();

            // Write C# code to prompt a user to input his/her first-name and then the output
            // Q.q3();

            // Write a C# program that asks the user to input n integer values and find the greatest value of the n values.
            // Q.q4();

            //Write a C# program which asks the user for two numbers and an operator to perform on them (+,-,x,/) and displays the result of that operation.
            // Q.q5a();
            // Q.q5b();

            //Write C# code to print the following pattern:
            // 1******
            // 12*****
            // 123****
            // 1234***
            // 12345**
            // 123456*
            // 1234567
            // Q.q6();

            //Write a C# program that determines a student’s grade according to new SLC grading
            // system. The program will read three types of scores(first-term score, mid-term score,
            // and final score) and determine the grade based on the following rules:
            // - Grade A: if the average score >=90%
            // - Grade B: if the average score >= 70% and <90%
            // - Grade C: if the average score >= 50% and <70%
            // - Grade E: if the average score >= 35% and < 50%
            // - Grade F: if the average score < 35%
            // Q.q7();

            //Write C# code to declare one integer variable, one float variable, and one string variable and assign 10, 12.5, and "50" to them respectively. 
            // a. Display their values on the screen. 
            // b. Add their values in floating point value and display the sum on the screen.
            // c. Concatenate their values and display the output on the screen.
            // Q.q8();

            //Write a C# program to allow a user to guess a number( from 1 to 6) that will be
            // randomly generated by computer. If the guess is correct, display “You won”. Otherwise
            // display “You lose”.
            // Q.q9();




        }
    }
}
